### ISSUE TITLE
Feature: User-can-view-dad-joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

when a user hovers over the emoji it gets larger
a user can click on the emoji icon 

## 📐 Functionality
create an interactive home page for users to view as soon as they load the app or the page

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/141523797-2573fc67-1cf4-43a0-ad09-0653d5d48717.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] first, create an HTML document and style it 
- [x] add background color to the body
- [x] add a smiling emoji to the body and center it to be in the middle of the page
- [x] underneath the emoji add a title of the app "dad jokes"
- [x] make the emoji larger when a user hovers over it.
- [x] a user can click the emoji.
- [x] when a user clicks the emoji they will be taken to the view page of the app 
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] [ ] when a user click on the emoji icon on the home page then they are taken to the view page
- [x] in the view page apply different styling for the header.
- [x] add the dad Jokes to the header.
- [x] add an underline to the container that's inside the header
- [x] create a `<main>` to contain all the content for the main body.
- [x] in main.js make sure that when a user first loads the view page they see an auto-generated dad joke
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
