### ISSUE TITLE
Feature: User can view their favorited joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view their favorite dad jokes in a separate window  
## 📐 Functionality
user will be able to click on the hamburger menu where the favorite feature tab will be and when a user click on the favorite tab it will take them to a new tab where all their favorite dad jokes will be saved 
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/147995548-78295cfb-34ee-4c5a-980d-8455c73bbb53.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 - [x] first, create a hamburger drop-down menu 
 - [x] in main.js we create a conditional that respond to the user's click 
 - [x] whenever a user clicks on the hamburger menu a favorite tab shows 
 - [x] when a user click on the favorite tab they're taken to a new tab where they can see their favorite dad jokes 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
