### ISSUE TITLE
Feature: User can delete a favorited dad joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user is able to delete a favorited dad joke
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

create a functionality where a user is able to delete a favorited dad joke
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/148627984-1f10c91a-286c-48dc-87ee-0f9ed890494c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a button designed as a trash can 
- [x] design the button
- [x] when a user click the trash can button a model pops up 
- [x] create an overlay that covers the main page
- [x] design the model to match the site design
- [x] add text inside the model that asks if the user is sure they want to delete the joke
- [x] add a cancel button and when a user clicks on the cancel it takes away the model and keeps all the jokes 
- [x] add a button that deletes the joke when a user clicks the delete button it deletes the joke they choose 
- [x] we need to add a number id to the li tree and then when a user chooses to delete a joke we need to compare the joke number id and if it matches then we delete it 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
