### ISSUE TITLE
Feature: User can view a dad joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view a dad joke
## 📐 Functionality
when a user clicks on the emoji button then they're taken to the view page where all the dad jokes are stored
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/141520664-b9b8b93b-312b-4ded-83f6-c0b5b32da763.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
