### ISSUE TITLE
Feature: User can view new dad joke and can go back to previous dad joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view a new dad joke by clicking on the right arrow button and can
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

a user can view a new dad joke by clicking the right arrow and can go back to the previous dad joke by clicking on the left arrow 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/142345624-2e07c30d-11a1-436c-bc7b-11d93d376619.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a left and right arrow button and style it.
- [x] when a user clicks on the right arrow auto-generate a new joke.
- [x] query select the right arrow
- [x] create an event listener for the right arrow 
- [x] create a function that responds to the right arrow when its clicked
- [x] create a code that auto-generates a new dad joke when the right arrow 
- [x]  in main.j query selected for the left button
- [x] add an event listener for the left button that listens for a click 
- [x] create a function that handles the left button event 
- [x] create a global variable that stores a dad joke when the right button is clicked 
- [x] create a for loop that loops over the array that is storing dad jokes
- [x] create a global count variable that gets incremented every time someone clicks the right arrow 
- [x] in the left arrow function decrement the count variable
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
