### ISSUE TITLE
Feature: User can view previous dad joke

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when a user clicks on the left button it goes back to the previous dad joke
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/141706122-63755964-be84-42ed-ac89-e95314849c37.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] in main.j query select for the left button
- [ ] add an event listener for the left button that listens for a click 
- [ ] create a function that handles the left button event 
- [ ] create a global variable that stores a dad joke when the right button is clicked 
- [ ] create a for loop that loops over the array that is storing dad jokes
- [ ] create a global count variable that gets incremented every time someone clicks the right arrow 
- [ ] in the left arrow function decrement the count variable
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
