### ISSUE TITLE
Feature: User can save a joke to their favorites list

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

a user would be able to favorite a dad joke

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user would be able to favorite a dad joke the dad joke would be added to their favorite list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90476994/142478151-714f9009-68e7-40cf-a6bf-1db623450a4a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] add a grin emoji and center it underneath the text 
- [x] add a joy/laughing emoji at the same position of the grin emoji then hide the laughing emoji
- [x] when a user clicks on the grin emoji it switches to the laughing emoji
- [x] when a user favorite a dad joke save that joke into an empty array
- [x] clicking on the emoji again would remove that joke from the array 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
